# Generated by Django 3.0.5 on 2020-04-13 23:11
#0002_auto_20200413_2311.py
from django.db import migrations, models
from accounts.api.serializers import (
    RegistrationSerializer,
)
from accounts.models import Account
from django.db import transaction
from rest_framework.authtoken.models import Token

# Run `makemigrations` and `migrate` first. 
# Then copy this file inside 'migrations' directory, and then 
# run `migrate` again, then delete it from the folder.
# keep a copy of this file outside the folder

@transaction.atomic
def add_main_users(apps, schema_editor):
    root_user = Account(
        email='youremail@address.com',
        username='Name',
        is_admin=True,
        is_active=True,
        is_staff=True,
        is_superuser=True
    )
    root_user.set_password('jP2K~mG)f}#w*-=?') # Your admin password
    root_user.save()
    anon_user = Account(
        email='anon@anon.anon',
        username='Anonymous',
        is_admin=False,
        is_active=True,
        is_staff=False,
        is_superuser=False
    )
    anon_user.set_password('r?_yFuDwCQHy8]bF')
    anon_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_main_users)
    ]
