# Generated by Django 3.0.5 on 2020-04-10 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pp_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hello_rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='image_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packager', models.CharField(blank=True, max_length=30)),
                ('top_img', models.ImageField(upload_to=pp_api.models.upload_top_location)),
                ('side_img', models.ImageField(upload_to=pp_api.models.upload_side_location)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
