# Generated by Django 3.0.5 on 2020-04-29 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pp_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_img', models.ImageField(upload_to=pp_api.models.top_img_path)),
                ('side_img', models.ImageField(upload_to=pp_api.models.side_img_path)),
                ('infer_img', models.ImageField(blank=True, null=True, upload_to=pp_api.models.infer_img_path)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Packager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('top_img', models.ImageField(upload_to=pp_api.models.top_img_path)),
                ('side_img', models.ImageField(upload_to=pp_api.models.side_img_path)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(default='-1', max_length=50)),
                ('count', models.IntegerField()),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
>>>>>>> 68370ef... - Reorganized models and improved their naming schemes.
            ],
        ),
        migrations.CreateModel(
            name='PPUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='PredictedImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('outer_size', models.IntegerField(blank=True, null=True)),
                ('inner_size', models.IntegerField(blank=True, null=True)),
                ('item_size', models.IntegerField(blank=True, null=True)),
                ('img_post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_api.ImagePost')),
                ('packager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pp_api.Packager')),
            ],
        ),
        migrations.AddField(
            model_name='imagepost',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_api.PPUsers'),
        ),
    ]
