# Generated by Django 3.0.5 on 2020-04-29 08:54
import random
from django.db import migrations
from pp_api.models import Packager
from django.db import transaction

BRANDS=["Amazon", "eBay", "Etsy", "Overstock", "Zappos", "Wish", "Alibaba", "AliExpress", "Walmart", "Sears", "Kohl's", "Costco", "Target", "Asos", "Brooklinen", "BHLDN", "Cuyana", "Konga", "Jumia", "Wayfair", "Adidas", "Nike", "Sony", "Ulta", "H&M", "Gucci", "Kors", "Ralph Lauren", "Prada", "HugoBoss", "TommyHilfiger", "Levi Strauss & Co", "Burberry", "Louis Vuitton", "Forever 21", "Fashion Nova", "J.Crew", "Lacoste", "Puma", "Timberland"
]

@transaction.atomic
def add_packager_data(apps, schema_editor):
    for brand in BRANDS:
        packager=Packager(
            name=brand.strip().replace(" ", "").lower(),
            display_name=brand,
            count=random.choice(range(500, 1000)),
            score=random.uniform(5,10)
        )
        packager.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pp_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_packager_data)
    ]
