# Generated by Django 3.0.3 on 2020-04-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hello_rest',
        ),
    ]
