# Generated by Django 3.0.5 on 2020-04-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_post',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
