# Generated by Django 3.0.5 on 2020-04-29 08:54
import random
from django.utils import timezone
from django.db import migrations
from django.db import transaction
from meta import BRANDS, MATERIALS
from pp_api.models import Packager

from pp_api.models import (
    PPUsers,
    ImagePost,
    PredictedImagePost
)

from meta import (
    DUMMY_NUM,
    DEFAULT_IMG,
    DEFAULT_EMAIL,
)


@transaction.atomic
def add_packager_data():
    packagers = []
    for brand in BRANDS:
        packager = Packager(
            name=brand.strip().replace(" ", "").lower(),
            brand_name=brand,
            count=random.choice(range(500, 1000)),
            score=random.uniform(5, 10)
        )
        packager.save()
        packagers.append(packager)
    return packagers


@transaction.atomic
def add_post_data(apps, schema_editor):
    packagers = add_packager_data()
    user = PPUsers(email=DEFAULT_EMAIL)
    user.save()
    for i in range(DUMMY_NUM):
        post = ImagePost(
            user_id=user,
            top_img=DEFAULT_IMG,
            side_img=DEFAULT_IMG,
            infer_img=None,
            date_posted=timezone.now()
        )
        post.save()
        pd_post = PredictedImagePost(
            img_post=post,
            packager=packagers[random.randint(0, len(packagers)-1)],
            materials=random.sample(MATERIALS, random.randint(0, len(MATERIALS)-1)),
            score=random.uniform(1, 10),
            outer_size=random.randint(3000, 4000),
            inner_size=random.randint(1000, 3000),
            item_size=random.randint(100, 1000)
        )
        pd_post.save()


class Migration(migrations.Migration):
    dependencies = [
        ('pp_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_post_data),
    ]
