# Generated by Django 3.0.5 on 2020-04-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp_api', '0002_image_post_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_post',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
